#!/usr/bin/env bash
set -euo pipefail

export PATH="/opt/homebrew/bin:/opt/homebrew/share/google-cloud-sdk/bin:${PATH:-}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"
FRONTEND_ENV="$ROOT/frontend/.env.local"
PROJECT_ID="eukov-drive"
KEY_RESOURCE="projects/1045117004627/locations/global/keys/ec167b5c-2006-46dc-9351-cb8bc0905628"
PROJECT_NUMBER="1045117004627"
SUPPORT_EMAIL="suyashverma.6701@gmail.com"

gcloud config set project "$PROJECT_ID" >/dev/null

if ! gcloud alpha --help >/dev/null 2>&1; then
  gcloud components install alpha --quiet
fi

API_KEY="$(gcloud services api-keys get-key-string "$KEY_RESOURCE" --project="$PROJECT_ID" --format='value(keyString)')"

BRAND="$(gcloud alpha iap oauth-brands list --project="$PROJECT_ID" --format='value(name)' 2>/dev/null | head -1 || true)"
if [[ -z "$BRAND" ]]; then
  BRAND="$(gcloud alpha iap oauth-brands create \
    --application_title="Eukov" \
    --support_email="$SUPPORT_EMAIL" \
    --project="$PROJECT_ID" \
    --format='value(name)')"
fi

CLIENT_RESOURCE="$(gcloud alpha iap oauth-clients list "$BRAND" --project="$PROJECT_ID" --filter="displayName:Eukov Web" --format='value(name)' 2>/dev/null | head -1 || true)"
if [[ -z "$CLIENT_RESOURCE" ]]; then
  CLIENT_RESOURCE="$(gcloud alpha iap oauth-clients create "$BRAND" \
    --display_name="Eukov Web" \
    --project="$PROJECT_ID" \
    --format='value(name)')"
fi

CLIENT_ID="$(gcloud alpha iap oauth-clients describe "$CLIENT_RESOURCE" --brand="$BRAND" --project="$PROJECT_ID" --format='value(name)' | awk -F/ '{print $NF}')"

upsert_env() {
  local key="$1" value="$2" file="$3"
  touch "$file"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    sed -i '' "s|^${key}=.*|${key}=${value}|" "$file"
  else
    printf '\n%s=%s\n' "$key" "$value" >>"$file"
  fi
}

upsert_env "NEXT_PUBLIC_GOOGLE_CLIENT_ID" "$CLIENT_ID" "$ENV_FILE"
upsert_env "NEXT_PUBLIC_GOOGLE_API_KEY" "$API_KEY" "$ENV_FILE"
upsert_env "NEXT_PUBLIC_GOOGLE_APP_ID" "$PROJECT_NUMBER" "$ENV_FILE"

cat >"$FRONTEND_ENV" <<EOF
# Generated by scripts/finish-google-drive-setup.sh
NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
NEXT_PUBLIC_GOOGLE_CLIENT_ID=$CLIENT_ID
NEXT_PUBLIC_GOOGLE_API_KEY=$API_KEY
NEXT_PUBLIC_GOOGLE_APP_ID=$PROJECT_NUMBER
EOF

echo "Google Drive credentials saved."
echo "Client ID suffix: ${CLIENT_ID: -20}"
echo "Project number: $PROJECT_NUMBER"
