#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$ROOT/.env"
FRONTEND_ENV="$ROOT/frontend/.env.local"

echo "==> EUKOV Google Drive setup (no billing / no payment method)"
echo
echo "Follow these steps in your browser (cancel any UPI / free-trial payment screens):"
echo
echo "  1. Sign in: https://console.cloud.google.com/"
echo "     - Skip or Cancel the free trial / UPI step"
echo
echo "  2. Create or pick a project (top bar) — name it e.g. Eukov"
echo
echo "  3. Enable APIs (replace PROJECT_ID in the URL with your project id):"
echo "     - Drive API:  https://console.cloud.google.com/apis/library/drive.googleapis.com"
echo "     - Picker API: https://console.cloud.google.com/apis/library/picker.googleapis.com"
echo
echo "  4. OAuth consent screen (Testing mode is fine):"
echo "     https://console.cloud.google.com/apis/credentials/consent"
echo "     - User type: External"
echo "     - App name: Eukov"
echo "     - Add YOUR email under Test users"
echo
echo "  5. Create OAuth client:"
echo "     https://console.cloud.google.com/apis/credentials/oauthclient"
echo "     - Web application"
echo "     - Authorized JavaScript origins: http://localhost:3000"
echo "     - Redirect URIs: leave empty"
echo
echo "  6. Create API key:"
echo "     https://console.cloud.google.com/apis/credentials"
echo "     - Create credentials → API key"
echo "     - (Optional) Restrict key to Google Drive API + Google Picker API"
echo
echo "  7. Project number (for APP ID):"
echo "     https://console.cloud.google.com/home/dashboard"
echo "     - Copy the Project number (digits only)"
echo

if command -v open >/dev/null 2>&1; then
  read -r -p "Open Google Cloud Console tabs now? [Y/n] " OPEN_TABS
  if [[ "${OPEN_TABS:-Y}" =~ ^[Yy]?$ ]]; then
    open "https://console.cloud.google.com/"
    open "https://console.cloud.google.com/apis/library/drive.googleapis.com"
    open "https://console.cloud.google.com/apis/library/picker.googleapis.com"
    open "https://console.cloud.google.com/apis/credentials/consent"
    open "https://console.cloud.google.com/apis/credentials"
    open "https://console.cloud.google.com/home/dashboard"
  fi
fi

echo
read -r -p "Paste OAuth Client ID: " CLIENT_ID
read -r -p "Paste API Key: " API_KEY
read -r -p "Paste Project number (APP ID): " APP_ID

if [[ -z "$CLIENT_ID" || -z "$API_KEY" || -z "$APP_ID" ]]; then
  echo "All three values are required."
  exit 1
fi

upsert_env() {
  local key="$1" value="$2" file="$3"
  touch "$file"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    if [[ "$(uname)" == "Darwin" ]]; then
      sed -i '' "s|^${key}=.*|${key}=${value}|" "$file"
    else
      sed -i "s|^${key}=.*|${key}=${value}|" "$file"
    fi
  else
    printf '\n%s=%s\n' "$key" "$value" >>"$file"
  fi
}

upsert_env "NEXT_PUBLIC_GOOGLE_CLIENT_ID" "$CLIENT_ID" "$ENV_FILE"
upsert_env "NEXT_PUBLIC_GOOGLE_API_KEY" "$API_KEY" "$ENV_FILE"
upsert_env "NEXT_PUBLIC_GOOGLE_APP_ID" "$APP_ID" "$ENV_FILE"

cat >"$FRONTEND_ENV" <<EOF
# Generated by scripts/setup-google-drive-no-billing.sh
NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
NEXT_PUBLIC_GOOGLE_CLIENT_ID=$CLIENT_ID
NEXT_PUBLIC_GOOGLE_API_KEY=$API_KEY
NEXT_PUBLIC_GOOGLE_APP_ID=$APP_ID
EOF

echo
echo "==> Saved to:"
echo "    $ENV_FILE"
echo "    $FRONTEND_ENV"
echo
echo "Restart the frontend, open the docket editor, and click Cloud."
echo "Sign in with the same Google account you added as a Test user."
