#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export PATH="/opt/homebrew/bin:/opt/homebrew/share/google-cloud-sdk/bin:${PATH:-}"

ENV_FILE="$ROOT/.env"
FRONTEND_ENV="$ROOT/frontend/.env.local"
PROJECT_ID="${GOOGLE_CLOUD_PROJECT:-eukov-drive}"
SUPPORT_EMAIL="${GOOGLE_SUPPORT_EMAIL:-}"

echo "==> EUKOV Google Drive setup"
echo "    Project root: $ROOT"
echo

if ! command -v gcloud >/dev/null 2>&1; then
  echo "==> Installing Google Cloud SDK..."
  brew install --cask gcloud-cli
  export PATH="/opt/homebrew/bin:/opt/homebrew/share/google-cloud-sdk/bin:${PATH:-}"
fi

if ! gcloud auth list --format="value(account)" 2>/dev/null | grep -q .; then
  echo "==> Sign in to Google Cloud (complete the browser prompt)..."
  gcloud auth login
fi

ACTIVE_ACCOUNT="$(gcloud auth list --filter=status:ACTIVE --format="value(account)" | head -1)"
if [[ -z "$SUPPORT_EMAIL" ]]; then
  SUPPORT_EMAIL="$ACTIVE_ACCOUNT"
fi
echo "    Using Google account: $ACTIVE_ACCOUNT"

if ! gcloud projects describe "$PROJECT_ID" >/dev/null 2>&1; then
  echo "==> Creating Google Cloud project: $PROJECT_ID"
  gcloud projects create "$PROJECT_ID" --name="Eukov"
fi

gcloud config set project "$PROJECT_ID"

echo "==> Enabling Google Drive API and Google Picker API..."
gcloud services enable drive.googleapis.com picker.googleapis.com --project="$PROJECT_ID"

PROJECT_NUMBER="$(gcloud projects describe "$PROJECT_ID" --format='value(projectNumber)')"
echo "    Project number (APP ID): $PROJECT_NUMBER"

echo "==> Configuring OAuth consent screen..."
gcloud alpha iap oauth-brands list --project="$PROJECT_ID" --format='value(name)' 2>/dev/null | grep -q . || \
  gcloud alpha iap oauth-brands create \
    --application_title="Eukov" \
    --support_email="$SUPPORT_EMAIL" \
    --project="$PROJECT_ID" 2>/dev/null || true

echo "==> Creating API key..."
API_KEY_NAME="eukov-picker-key"
EXISTING_KEY="$(gcloud services api-keys list --project="$PROJECT_ID" --filter="displayName:$API_KEY_NAME" --format='value(name)' 2>/dev/null | head -1 || true)"

if [[ -n "$EXISTING_KEY" ]]; then
  API_KEY="$(gcloud services api-keys get-key-string "$EXISTING_KEY" --project="$PROJECT_ID" --format='value(keyString)')"
  echo "    Reusing existing API key."
else
  KEY_RESOURCE="$(gcloud services api-keys create \
    --display-name="$API_KEY_NAME" \
    --api-target=service=picker.googleapis.com \
    --api-target=service=drive.googleapis.com \
    --project="$PROJECT_ID" \
    --format='value(name)')"
  API_KEY="$(gcloud services api-keys get-key-string "$KEY_RESOURCE" --project="$PROJECT_ID" --format='value(keyString)')"
fi

CREDENTIALS_URL="https://console.cloud.google.com/apis/credentials/oauthclient?project=${PROJECT_ID}"
CONSENT_URL="https://console.cloud.google.com/apis/credentials/consent?project=${PROJECT_ID}"

echo
echo "==> Create OAuth Web Client ID (required for Cloud button)"
echo "    A browser tab will open. Use these settings:"
echo "    - Application type: Web application"
echo "    - Name: Eukov Web"
echo "    - Authorized JavaScript origins: http://localhost:3000"
echo "    - Leave redirect URIs empty"
echo
if command -v open >/dev/null 2>&1; then
  open "$CREDENTIALS_URL"
  open "$CONSENT_URL"
fi

read -r -p "Paste OAuth Client ID from the console: " CLIENT_ID

if [[ -z "$CLIENT_ID" || -z "$API_KEY" ]]; then
  echo "Setup incomplete — missing Client ID or API key."
  exit 1
fi

upsert_env() {
  local key="$1"
  local value="$2"
  local file="$3"
  touch "$file"
  if grep -q "^${key}=" "$file" 2>/dev/null; then
    if [[ "$(uname)" == "Darwin" ]]; then
      sed -i '' "s|^${key}=.*|${key}=${value}|" "$file"
    else
      sed -i "s|^${key}=.*|${key}=${value}|" "$file"
    fi
  else
    printf '\n%s=%s\n' "$key" "$value" >>"$file"
  fi
}

upsert_env "NEXT_PUBLIC_GOOGLE_CLIENT_ID" "$CLIENT_ID" "$ENV_FILE"
upsert_env "NEXT_PUBLIC_GOOGLE_API_KEY" "$API_KEY" "$ENV_FILE"
upsert_env "NEXT_PUBLIC_GOOGLE_APP_ID" "$PROJECT_NUMBER" "$ENV_FILE"

cat >"$FRONTEND_ENV" <<EOF
# Generated by scripts/setup-google-drive.sh
NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
NEXT_PUBLIC_GOOGLE_CLIENT_ID=$CLIENT_ID
NEXT_PUBLIC_GOOGLE_API_KEY=$API_KEY
NEXT_PUBLIC_GOOGLE_APP_ID=$PROJECT_NUMBER
EOF

echo
echo "==> Done. Credentials saved to:"
echo "    $ENV_FILE"
echo "    $FRONTEND_ENV"
echo
echo "On the OAuth consent screen, add $ACTIVE_ACCOUNT as a Test user if the app is in Testing mode."
echo "Restart the frontend, then click Cloud in the draft editor."
